"""spec 1.1 data model

Revision ID: 0001
Revises:
Create Date: 2026-10-08 22:14:39.299871

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.schema.CreateSequence(sa.Sequence("order_no_seq", start=1000)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "scope", "key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kakao_id", sa.String(length=64), nullable=True),
        sa.Column("is_test_account", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kakao_id", "role"),
    )
    op.create_table(
        "farms",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("producer_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("intro", sa.Text(), nullable=False),
        sa.Column("photo", sa.String(length=500), nullable=True),
        sa.Column("main_items", sa.String(length=200), nullable=False),
        sa.Column("contact_phone", sa.String(length=32), nullable=False),
        sa.Column("approval_status", sa.String(length=16), nullable=False),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("suspend_reason", sa.Text(), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("producer_id"),
    )
    op.create_table(
        "shipping_addresses",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("recipient_name", sa.String(length=100), nullable=False),
        sa.Column("recipient_phone", sa.String(length=32), nullable=False),
        sa.Column("postal_code", sa.String(length=16), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("address_detail", sa.String(length=300), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shipping_addresses_user_id"), "shipping_addresses", ["user_id"], unique=False
    )
    op.create_table(
        "broadcasts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("farm_id", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("photos", sa.JSON(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("reaction_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_broadcasts_created_at"), "broadcasts", ["created_at"], unique=False)
    op.create_index(op.f("ix_broadcasts_farm_id"), "broadcasts", ["farm_id"], unique=False)
    op.create_table(
        "follows",
        sa.Column("consumer_id", sa.String(length=64), nullable=False),
        sa.Column("farm_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["consumer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("consumer_id", "farm_id"),
    )
    op.create_table(
        "product_drafts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("farm_id", sa.String(length=64), nullable=False),
        sa.Column("input_text", sa.Text(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("missing_fields", sa.JSON(), nullable=False),
        sa.Column("failed", sa.Boolean(), nullable=False),
        sa.Column("price_mentioned", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_drafts_farm_id"), "product_drafts", ["farm_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("farm_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("variety", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("farmer_note", sa.Text(), nullable=False),
        sa.Column("photos", sa.JSON(), nullable=False),
        sa.Column("grade", sa.String(length=20), nullable=True),
        sa.Column("expected_brix", sa.Float(), nullable=True),
        sa.Column("measured_brix", sa.Float(), nullable=True),
        sa.Column("measured_brix_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("brix_record_count", sa.Integer(), nullable=False),
        sa.Column("delivery_start", sa.Date(), nullable=True),
        sa.Column("delivery_end", sa.Date(), nullable=True),
        sa.Column("max_delay_until", sa.Date(), nullable=True),
        sa.Column("shipping_fee_type", sa.String(length=16), nullable=False),
        sa.Column("shipping_fee", sa.Integer(), nullable=False),
        sa.Column("remote_area_fee", sa.Integer(), nullable=False),
        sa.Column("max_quantity_per_order", sa.Integer(), nullable=False),
        sa.Column("info", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("pending_reapproval", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_farm_id"), "products", ["farm_id"], unique=False)
    op.create_table(
        "product_options",
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("note", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("product_id", "id"),
    )
    op.create_table(
        "reactions",
        sa.Column("broadcast_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("broadcast_id", "user_id"),
    )
    op.create_table(
        "stages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("starts_at", sa.Date(), nullable=False),
        sa.Column("ends_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stages_product_id"), "stages", ["product_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("order_no", sa.String(length=32), nullable=False),
        sa.Column("consumer_id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("option_id", sa.String(length=64), nullable=False),
        sa.Column("stage_id", sa.String(length=64), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Integer(), nullable=False),
        sa.Column("shipping_fee", sa.Integer(), nullable=False),
        sa.Column("remote_area_fee", sa.Integer(), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("delivery_start", sa.Date(), nullable=False),
        sa.Column("delivery_end", sa.Date(), nullable=False),
        sa.Column("proposed_delivery_start", sa.Date(), nullable=True),
        sa.Column("proposed_delivery_end", sa.Date(), nullable=True),
        sa.Column("recipient_name", sa.String(length=100), nullable=False),
        sa.Column("recipient_phone", sa.String(length=32), nullable=False),
        sa.Column("postal_code", sa.String(length=16), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("address_detail", sa.String(length=300), nullable=False),
        sa.Column("delivery_note", sa.String(length=100), nullable=True),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consent_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("carrier", sa.String(length=16), nullable=True),
        sa.Column("tracking_number", sa.String(length=50), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refund_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["consumer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id", "option_id"],
            ["product_options.product_id", "product_options.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_no"),
    )
    op.create_index(op.f("ix_orders_consumer_id"), "orders", ["consumer_id"], unique=False)
    op.create_index(op.f("ix_orders_product_id"), "orders", ["product_id"], unique=False)
    op.create_table(
        "stage_allocations",
        sa.Column("stage_id", sa.String(length=64), nullable=False),
        sa.Column("option_id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reserved_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id", "option_id"],
            ["product_options.product_id", "product_options.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
        ),
        sa.PrimaryKeyConstraint("stage_id", "option_id"),
    )
    op.create_table(
        "stage_prices",
        sa.Column("stage_id", sa.String(length=64), nullable=False),
        sa.Column("option_id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id", "option_id"],
            ["product_options.product_id", "product_options.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
        ),
        sa.PrimaryKeyConstraint("stage_id", "option_id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_table("stage_prices")
    op.drop_table("stage_allocations")
    op.drop_index(op.f("ix_orders_product_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_consumer_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_stages_product_id"), table_name="stages")
    op.drop_table("stages")
    op.drop_table("reactions")
    op.drop_table("product_options")
    op.drop_index(op.f("ix_products_farm_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_product_drafts_farm_id"), table_name="product_drafts")
    op.drop_table("product_drafts")
    op.drop_table("follows")
    op.drop_index(op.f("ix_broadcasts_farm_id"), table_name="broadcasts")
    op.drop_index(op.f("ix_broadcasts_created_at"), table_name="broadcasts")
    op.drop_table("broadcasts")
    op.drop_index(op.f("ix_shipping_addresses_user_id"), table_name="shipping_addresses")
    op.drop_table("shipping_addresses")
    op.drop_table("farms")
    op.drop_table("users")
    op.drop_table("idempotency_records")
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("order_no_seq")))
