"""spec 1.2 messaging

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 22:45:01.636283

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "farm_ai_settings",
        sa.Column("farm_id", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("small_order_policy", sa.Text(), nullable=False),
        sa.Column("reservation_shipping_policy", sa.Text(), nullable=False),
        sa.Column("faqs", sa.JSON(), nullable=False),
        sa.Column("handoff_topics", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("farm_id"),
    )
    op.create_table(
        "room_replies",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("farm_id", sa.String(length=64), nullable=False),
        sa.Column("consumer_id", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["consumer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_room_replies_consumer_id"), "room_replies", ["consumer_id"], unique=False
    )
    op.create_index(
        op.f("ix_room_replies_created_at"), "room_replies", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_room_replies_farm_id"), "room_replies", ["farm_id"], unique=False)
    op.create_table(
        "threads",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("farm_id", sa.String(length=64), nullable=False),
        sa.Column("consumer_id", sa.String(length=64), nullable=False),
        sa.Column("ai_mode", sa.String(length=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("consumer_last_read_message_id", sa.String(length=64), nullable=True),
        sa.Column("producer_last_read_message_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["consumer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("farm_id", "consumer_id"),
    )
    op.create_index(op.f("ix_threads_consumer_id"), "threads", ["consumer_id"], unique=False)
    op.create_index(op.f("ix_threads_farm_id"), "threads", ["farm_id"], unique=False)
    op.create_table(
        "thread_messages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("sender_type", sa.String(length=16), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("photos", sa.JSON(), nullable=False),
        sa.Column("attachment_ids", sa.JSON(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("inquiry_id", sa.String(length=64), nullable=True),
        sa.Column("source_summary", sa.Text(), nullable=True),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("settings_version", sa.Integer(), nullable=True),
        sa.Column("handoff_status", sa.String(length=16), nullable=True),
        sa.Column("masked", sa.Boolean(), nullable=False),
        sa.Column("needs_human", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seq"),
    )
    op.create_index(
        op.f("ix_thread_messages_created_at"), "thread_messages", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_thread_messages_thread_id"), "thread_messages", ["thread_id"], unique=False
    )
    op.create_table(
        "escalations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("thread_message_id", sa.String(length=64), nullable=True),
        sa.Column("context", sa.String(length=200), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_message_id"],
            ["thread_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_escalations_thread_id"), "escalations", ["thread_id"], unique=False)
    op.add_column(
        "broadcasts", sa.Column("videos", sa.JSON(), server_default=sa.text("'[]'"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("broadcasts", "videos")
    op.drop_index(op.f("ix_escalations_thread_id"), table_name="escalations")
    op.drop_table("escalations")
    op.drop_index(op.f("ix_thread_messages_thread_id"), table_name="thread_messages")
    op.drop_index(op.f("ix_thread_messages_created_at"), table_name="thread_messages")
    op.drop_table("thread_messages")
    op.drop_index(op.f("ix_threads_farm_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_consumer_id"), table_name="threads")
    op.drop_table("threads")
    op.drop_index(op.f("ix_room_replies_farm_id"), table_name="room_replies")
    op.drop_index(op.f("ix_room_replies_created_at"), table_name="room_replies")
    op.drop_index(op.f("ix_room_replies_consumer_id"), table_name="room_replies")
    op.drop_table("room_replies")
    op.drop_table("farm_ai_settings")
    # ### end Alembic commands ###
