"""spec 1.2 settings inquiries

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 22:56:57.578200

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "private_attachments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("uploader_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("thread_id", sa.String(length=64), nullable=True),
        sa.Column("mime_type", sa.String(length=32), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("bound", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploader_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_private_attachments_created_at"),
        "private_attachments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_private_attachments_uploader_id"),
        "private_attachments",
        ["uploader_id"],
        unique=False,
    )
    op.create_table(
        "farm_ai_settings_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("farm_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("saved_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["saved_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_farm_ai_settings_history_farm_id"),
        "farm_ai_settings_history",
        ["farm_id"],
        unique=False,
    )
    op.create_table(
        "order_inquiries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("attachment_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["thread_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_inquiries_order_id"), "order_inquiries", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_inquiries_thread_id"), "order_inquiries", ["thread_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_inquiries_thread_id"), table_name="order_inquiries")
    op.drop_index(op.f("ix_order_inquiries_order_id"), table_name="order_inquiries")
    op.drop_table("order_inquiries")
    op.drop_index(
        op.f("ix_farm_ai_settings_history_farm_id"), table_name="farm_ai_settings_history"
    )
    op.drop_table("farm_ai_settings_history")
    op.drop_index(op.f("ix_private_attachments_uploader_id"), table_name="private_attachments")
    op.drop_index(op.f("ix_private_attachments_created_at"), table_name="private_attachments")
    op.drop_table("private_attachments")
    # ### end Alembic commands ###
